# Generated by Django 5.0 on 2025-09-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.CharField(choices=[('none', 'None'), ('sponsor', 'Sponsorship available')], default='none', max_length=32),
        ),
    ]
