# Generated by Django 5.0 on 2025-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='desired_companies',
            field=models.TextField(blank=True, help_text='Comma-separated desired companies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='desired_positions',
            field=models.TextField(blank=True, help_text='Comma-separated desired positions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
